{% set name = "tintx" %}
{% set version = "2022.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tintx-{{ version }}.tar.gz
  sha256: 6fa4868b61c558c7f2c300ac6409ea381c6dcf9470586683c67b0e3b113b8b89

build:
  entry_points:
    - tintx = tintx.cli:tintx
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - cartopy
    - cftime
    - click
    - dask-core
    - geopandas
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas
    - python >=3.7
    - rasterio
    - scipy
    - shapely
    - pytables
    - tqdm
    - typing-extensions
    - xarray

test:
  imports:
    - tintx
  commands:
    - pip check
    - tintx --help
  requires:
    - pip

about:
  home: https://github.com/antarcticrainforest/tintX
  summary: Tracking facility to track rainfall and other non-continous data.
  dev_url: https://github.com/antarcticrainforest/tintX
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - antarcticrainforest
